---
change-template: "- $TITLE @$AUTHOR (#$NUMBER)"
sort-direction: ascending
filter-by-commitish: false

categories:
  - title: "🚨 Breaking changes"
    labels:
      - "breaking-change"
  - title: "✨ New features"
    labels:
      - "new-feature"
  - title: "🐛 Bug fixes"
    labels:
      - "bugfix"
  - title: "🚀 Enhancements"
    labels:
      - "enhancement"
      - "refactor"
      - "performance"
  - title: "🧰 Maintenance"
    labels:
      - "maintenance"
      - "ci"
  - title: "📚 Documentation"
    labels:
      - "documentation"
  - title: "⬆️ Dependency updates"
    labels:
      - "dependencies"
    collapse-after: 1

include-labels:
  - "breaking-change"
  - "new-feature"
  - "bugfix"
  - "enhancement"
  - "refactor"
  - "performance"
  - "maintenance"
  - "ci"
  - "documentation"
  - "dependencies"

template: |
  ## What’s changed

  $CHANGES
