---
name: Release changelog

# yamllint disable-line rule:truthy
on:
  push:
    tags:
      - "*.*.*"

permissions:
  contents: write
  pull-requests: write

jobs:
  changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v7
        with:
          ref: mc
          token: ${{ secrets.GH_TOKEN }}

      - uses: rhysd/changelog-from-release/action@v3
        with:
          file: CHANGELOG.md
          pull_request: true
          commit_summary_template: "Update the changelog for %s"
          args: -c
          github_token: ${{ secrets.GH_TOKEN }}
